### ISSUE TITLE
 Error: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by bingryan** [devicons/public-upload-to-imgur#29]

**Comment by Panquesito7** [comment]
Hello. Could you please explain where is this error shown? 🤔

**Comment by bingryan** [comment]
path add 8M png image

**Comment by Panquesito7** [comment]
Could you provide more details and examples or such? I'm not sure I understand. 😅

**Comment by bingryan** [comment]
```
steps:
  - name: Upload a picture
    uses: devicons/public-upload-to-imgur@v2.2.2  # Use this for the most stable version
    with:
      path: ./img.png  # required
      client_id: ${{secrets.IMGUR_CLIENT_ID}}  # required
      description: My picture  # optional
```

img.png is 8M image

then, get error: Request body larger than maxBodyLength limi
